### ISSUE TITLE
Code formatting todo

### ISSUE THREAD

**Issue by lawrenceakka** [SoCo/SoCo#349]
There are a few code formatting issues I would like to correct:
- [x] Docstring formatting to be PEP257 compliant (using [docformatter --no-blank](https://pypi.python.org/pypi/docformatter))
- [ ] Ensure docstring params are in accordance with the Google style guide
- [x] Import reordering to be pep8 compliant, and easier to follow (i.e. in the order stdlib, third party, local) (using [isort](https://pypi.python.org/pypi/docformatter)). I prefer the 'vertical hanging indent' option (option 3 on the homepage.
- [x] Ensuring presence of appropriate `from __future__` imports, and general consistency of file headers
- [x] Consistent use of express relative imports (i.e. `from . import`)

Does anyone have comments? If, not, I will produce a PR

**Comment by KennethNielsen** [comment]
Another issue, that also touches the docstrings, us to napoleonize them. This will however probably be a bigger change, so maybe it is something we should do on a module by module basis.

With regards to docformatter I must admit that I have always had a hard time with that extra blanc line at the end of multiline doc strings, especially because if I remember it correctly, it was basically made a recommendation to make it easier to use auto linebrraking features of cettains editor (or maybe just 1, emacs), which although I use it, I think is a bit silly. In any case, it is in pep257 so ok by me.

**Comment by lawrenceakka** [comment]
@KennethNielsen Docformatter offers:
```
--no-blank            do not add blank line after description
```

I'm happy with that.

**Comment by KennethNielsen** [comment]
That would be cool. BTW sorry about barely legible English in the previous post. That was from my phone.

**Comment by pwt** [comment]
Superseded by other changes.
